<script setup lang="ts">
import type { ShareHitRow, ShareLinkDetail, ShareLinkRow, ShareLinks, ShareMintResult } from '#shared/analytics/ops'
import type { DataColumn } from '~/components/ops/DataTable.vue'
import type { OpsFetchError } from '~/composables/useOpsFetch'
import { copyText } from '~/utils/csv'

definePageMeta({ layout: 'ops', middleware: 'ops-auth' })

useHead({ title: 'OPS // SHARE' })

const fmt = useOpsFormat()
const { linkTo } = useOpsFilters()

type Row = Record<string, unknown>

/**
 * SHARE — one link per named recipient, and honest evidence of circulation.
 *
 * There is no forwarding tree here on purpose: no URL rewriting, no
 * per-visitor token, no chain. A link opened by several distinct people is
 * reported as FORWARDED with the recipient UNKNOWN, which is the true state of
 * knowledge. The only name on this page is the label the owner typed himself.
 *
 * The view is not windowed by the filter bar: a link is a thing, not a period.
 */
const { data, status, error, refresh } = useOpsFetch<ShareLinks>('/api/ops/share')

// ------------------------------------------------------------------ minting

const label = ref('')
const note = ref('')
const channel = ref('')
const minting = ref(false)
const mintFault = ref<string | null>(null)
const minted = ref<ShareMintResult | null>(null)

async function mint() {
  if (minting.value || label.value.trim().length === 0) return
  minting.value = true
  mintFault.value = null
  try {
    minted.value = await opsFetch<ShareMintResult>('/api/ops/share', {
      method: 'POST',
      body: { label: label.value, note: note.value, channel: channel.value },
    })
    label.value = ''
    note.value = ''
    channel.value = ''
    await refresh()
  } catch (err) {
    mintFault.value = (err as OpsFetchError).message
  } finally {
    minting.value = false
  }
}

// ------------------------------------------------------------------- detail

const selected = ref<string | null>(null)
const detail = ref<ShareLinkDetail | null>(null)
const detailFault = ref<OpsFetchError | null>(null)
const detailLoading = ref(false)
let detailSeq = 0

async function loadDetail(token: string) {
  const my = ++detailSeq
  detailLoading.value = true
  detailFault.value = null
  try {
    const res = await opsFetch<ShareLinkDetail>(`/api/ops/share/${token}`)
    if (my !== detailSeq) return
    detail.value = res
  } catch (err) {
    if (my !== detailSeq) return
    detail.value = null
    detailFault.value = err as OpsFetchError
  } finally {
    if (my === detailSeq) detailLoading.value = false
  }
}

/** Click the token to expand a link; click it again to collapse. */
async function toggle(token: string) {
  if (selected.value === token) {
    selected.value = null
    detail.value = null
    return
  }
  selected.value = token
  detail.value = null
  await loadDetail(token)
}

async function setRevoked(token: string, revoked: boolean) {
  try {
    await opsFetch(`/api/ops/share/${token}/revoke`, { method: 'POST', body: { revoked } })
    await refresh()
    if (selected.value === token) await loadDetail(token)
  } catch (err) {
    mintFault.value = (err as OpsFetchError).message
  }
}

// -------------------------------------------------------------------- copy

const copied = ref('')
async function copy(text: string, key: string) {
  if (await copyText(text)) {
    copied.value = key
    setTimeout(() => (copied.value = ''), 1500)
  }
}

// ------------------------------------------------------------------- tables

function chips(v: unknown): string[] {
  return Array.isArray(v) ? v.map(String).filter(Boolean) : []
}

/** "3 PEOPLE · 2 ORGS" — the evidence, never a bare verdict. */
function evidence(row: Row): string {
  const readers = Number(row.readers ?? 0)
  const orgs = chips(row.orgs).length
  const bits: string[] = []
  if (readers > 0) bits.push(`${fmt.num(readers)} ${readers === 1 ? 'PERSON' : 'PEOPLE'}`)
  if (orgs > 0) bits.push(`${fmt.num(orgs)} ORG${orgs === 1 ? '' : 'S'}`)
  return bits.join(' · ')
}

const columns: DataColumn[] = [
  { key: 'token', label: 'TOKEN', width: '6em' },
  { key: 'label', label: 'SENT TO', ellipsis: true },
  { key: 'channel', label: 'CHANNEL' },
  { key: 'opens', label: 'OPENS', title: 'every document request carrying the link' },
  { key: 'views', label: 'VIEWS', title: 'opens from a browser, not a preview bot' },
  { key: 'unfurls', label: 'UNFURLS', title: 'link previews generated by a chat / social platform' },
  { key: 'readers', label: 'PEOPLE', title: 'distinct visitor identities among the sessions carrying the link' },
  { key: 'sessions', label: 'SESSIONS' },
  { key: 'platforms', label: 'PLATFORMS', sortable: false },
  { key: 'orgs', label: 'ORGS', sortable: false, ellipsis: true },
  { key: 'countries', label: 'COUNTRIES', sortable: false },
  { key: 'forwarded', label: 'FORWARDED', title: 'more than one reader, or more than one organisation — recipient unknown' },
  { key: 'lastHit', label: 'LAST SEEN', format: v => fmt.dateTime(v), numeric: true, align: 'left' },
  { key: 'createdAt', label: 'MINTED', format: v => fmt.dateTime(v), numeric: true, align: 'left' },
  { key: 'state', label: 'STATE', sortable: false, align: 'center' },
]

const rows = computed<Row[]>(() =>
  (data.value?.links ?? []).map((l: ShareLinkRow) => ({ ...l, state: l.revoked ? 'REVOKED' : 'LIVE' })),
)

const hitColumns: DataColumn[] = [
  { key: 'ts', label: 'WHEN', format: v => fmt.dateTimeSec(v), numeric: true, align: 'left' },
  { key: 'kind', label: 'KIND', format: v => String(v).toUpperCase() },
  { key: 'agent', label: 'PLATFORM' },
  { key: 'as_org', label: 'ORGANIZATION', ellipsis: true },
  { key: 'country', label: 'COUNTRY' },
  { key: 'referrer_host', label: 'REFERRER' },
  { key: 'path', label: 'PATH', ellipsis: true },
]

const hitRows = computed<Row[]>(() => (detail.value?.hits ?? []) as unknown as Row[])

const sessionColumns: DataColumn[] = [
  { key: 'started_at', label: 'STARTED', format: v => fmt.dateTime(v), numeric: true, align: 'left' },
  { key: 'as_org', label: 'ORGANIZATION', ellipsis: true },
  { key: 'country', label: 'COUNTRY' },
  { key: 'device_type', label: 'DEVICE' },
  { key: 'browser', label: 'BROWSER' },
  { key: 'pageviews', label: 'PAGES' },
  { key: 'active_ms', label: 'ACTIVE', format: v => fmt.mmss(v), numeric: true },
  { key: 'max_scroll_pct', label: 'SCROLL %', format: v => fmt.pct(v, 0) },
]

const sessionRows = computed<Row[]>(() => (detail.value?.sessions ?? []) as unknown as Row[])

function sessionTo(row: Row): string {
  return linkTo(`/ops/sessions/${String(row.sid ?? '')}`)
}

const selectedLink = computed<ShareLinkRow | null>(() => detail.value?.link ?? null)
</script>

<template>
  <div class="sh">
    <p class="sh__note label">
      ONE LINK PER NAMED RECIPIENT · NO URL REWRITING · NO PER-VISITOR TOKEN · NO CHAIN · SEVERAL READERS ON ONE LINK = FORWARDED, RECIPIENT UNKNOWN
    </p>

    <Panel title="MINT // A LINK FOR ONE RECIPIENT">
      <form class="sh__mint" @submit.prevent="mint">
        <label class="label" for="sh-label">SENT TO</label>
        <input
          id="sh-label"
          v-model="label"
          data-testid="share-label"
          class="sh__input"
          type="text"
          maxlength="120"
          placeholder="Jane Okafor — Acme"
          spellcheck="false"
        >
        <label class="label" for="sh-channel">CHANNEL</label>
        <input
          id="sh-channel"
          v-model="channel"
          data-testid="share-channel"
          class="sh__input"
          type="text"
          maxlength="40"
          placeholder="email / linkedin / call"
          spellcheck="false"
        >
        <label class="label" for="sh-note">NOTE</label>
        <input
          id="sh-note"
          v-model="note"
          data-testid="share-note"
          class="sh__input"
          type="text"
          maxlength="400"
          placeholder="optional — why this link exists"
        >
        <button
          class="sh__submit"
          type="submit"
          data-testid="share-mint"
          :disabled="minting || label.trim().length === 0"
        >
          {{ minting ? '... MINTING' : 'MINT LINK' }}
        </button>
      </form>

      <p v-if="mintFault" class="sh__fault" role="alert">MINT FAULT // {{ mintFault.toUpperCase() }}</p>
      <div v-if="minted" class="sh__minted">
        <span class="label">LINK</span>
        <code class="sh__url" data-testid="share-minted-url">{{ minted.url }}</code>
        <button type="button" class="sh__btn label" data-testid="share-copy" @click="copy(minted.url, 'minted')">
          {{ copied === 'minted' ? 'COPIED' : 'COPY' }}
        </button>
      </div>
      <p class="sh__note label">
        THE LABEL IS THE ONLY NAME THIS FEATURE EVER RECORDS · EVERY OTHER OPENER IS DESCRIBED BY ORGANIZATION, COUNTRY AND DEVICE
      </p>
    </Panel>

    <p v-if="error" class="sh__fault">{{ opsFault(error, 'share') }}</p>
    <p v-else-if="!data && status === 'pending'" class="sh__poll label">... POLLING</p>

    <template v-if="data">
      <Panel title="SHARE LINKS // WHERE THE RÉSUMÉ WENT">
        <DataTable
          :columns="columns"
          :rows="rows"
          row-key="token"
          row-testid="share-row"
          :sort="{ key: 'createdAt', dir: 'desc' }"
          empty="NO DATA // SHARE LINKS"
          dense
        >
          <template #cell-token="{ row }">
            <button type="button" class="sh__tok" :class="{ 'sh__tok--on': selected === row.token }" @click.stop="toggle(String(row.token))">
              {{ row.token }}
            </button>
          </template>
          <template #cell-platforms="{ value }">
            <span class="sh__chips">
              <span v-for="p in chips(value)" :key="p" class="sh__chip sh__chip--on label">{{ p }}</span>
              <span v-if="chips(value).length === 0">—</span>
            </span>
          </template>
          <template #cell-orgs="{ value }">
            <span class="sh__chips">
              <span v-for="o in chips(value)" :key="o" class="sh__chip label">{{ o }}</span>
              <span v-if="chips(value).length === 0">—</span>
            </span>
          </template>
          <template #cell-countries="{ value }">
            <span class="sh__chips">
              <span v-for="c in chips(value)" :key="c" class="sh__chip label">{{ c }}</span>
              <span v-if="chips(value).length === 0">—</span>
            </span>
          </template>
          <template #cell-forwarded="{ row, value }">
            <span v-if="value" class="sh__fwd label">FORWARDED // {{ evidence(row) }}</span>
            <span v-else class="sh__quiet">—</span>
          </template>
          <template #cell-state="{ row }">
            <span class="sh__state label" :class="{ 'sh__state--off': row.revoked }">{{ row.state }}</span>
            <button type="button" class="sh__btn label" @click.stop="setRevoked(String(row.token), !row.revoked)">
              {{ row.revoked ? 'RESTORE' : 'REVOKE' }}
            </button>
          </template>
        </DataTable>
        <p class="sh__note label">
          PEOPLE = DISTINCT VISITOR IDENTITIES AMONG THE SESSIONS CARRYING THE LINK · A REVOKED LINK IS STILL RECORDED, THAT IS THE POINT
        </p>
      </Panel>

      <template v-if="selected">
        <p v-if="detailFault" class="sh__fault">{{ opsFault(detailFault, 'share link') }}</p>
        <p v-else-if="detailLoading && !detail" class="sh__poll label">... POLLING</p>

        <template v-if="detail && selectedLink">
          <Panel :title="`LINK ${selectedLink.token} // ${selectedLink.label.toUpperCase()}`" teal>
            <div class="sh__head">
              <code class="sh__url">{{ selectedLink.url }}</code>
              <button type="button" class="sh__btn label" @click="copy(selectedLink.url, 'detail')">
                {{ copied === 'detail' ? 'COPIED' : 'COPY' }}
              </button>
              <span class="sh__state label" :class="{ 'sh__state--off': selectedLink.revoked }">
                {{ selectedLink.revoked ? 'REVOKED' : 'LIVE' }}
              </span>
              <span v-if="selectedLink.channel" class="sh__chip label">{{ selectedLink.channel }}</span>
            </div>
            <p v-if="selectedLink.note" class="sh__prose">{{ selectedLink.note }}</p>
            <p class="sh__verdict label">
              <template v-if="selectedLink.forwarded">
                FORWARDED, RECIPIENT UNKNOWN // {{ evidence({ ...selectedLink }) }} · ONLY {{ selectedLink.label.toUpperCase() }} WAS NAMED BY YOU
              </template>
              <template v-else-if="selectedLink.opens > 0">
                NO EVIDENCE OF FORWARDING // {{ evidence({ ...selectedLink }) || 'PREVIEW FETCHES ONLY' }}
              </template>
              <template v-else>
                NEVER OPENED
              </template>
            </p>
          </Panel>

          <Panel title="HITS // EVERY REQUEST THAT CARRIED THE LINK">
            <DataTable
              :columns="hitColumns"
              :rows="hitRows"
              row-key="id"
              row-testid="share-hit-row"
              :sort="{ key: 'ts', dir: 'desc' }"
              empty="NO DATA // HITS"
              dense
              :limit="50"
            >
              <template #cell-kind="{ value }">
                <span class="sh__kind label" :class="`sh__kind--${String(value)}`">{{ String(value).toUpperCase() }}</span>
              </template>
            </DataTable>
            <p class="sh__note label">NO IP AND NO RAW USER AGENT IS STORED HERE · PLATFORM COMES FROM A NAMED PREVIEW-BOT TABLE</p>
          </Panel>

          <Panel title="SESSIONS // WHAT THE LINK PRODUCED">
            <DataTable
              :columns="sessionColumns"
              :rows="sessionRows"
              row-key="sid"
              row-testid="share-session-row"
              :sort="{ key: 'started_at', dir: 'desc' }"
              :row-to="sessionTo"
              empty="NO DATA // SESSIONS"
              dense
            />
            <p class="sh__note label">ATTRIBUTED THROUGH SESSION_NET.SHARE_TOKEN — THE COOKIE THE DOCUMENT REQUEST SET, FIRST WRITE WINS</p>
          </Panel>
        </template>
      </template>
    </template>
  </div>
</template>

<style scoped>
.sh {
  display: grid;
  gap: var(--space-4);
}

.sh__poll {
  color: var(--text-faint);
}

.sh__fault {
  color: var(--red);
  font-size: var(--fs-micro);
  letter-spacing: 0.14em;
  text-transform: uppercase;
}

.sh__note {
  margin-top: var(--space-2);
  color: var(--text-faint);
}

.sh__mint {
  display: grid;
  grid-template-columns: auto minmax(0, 1fr);
  align-items: center;
  gap: var(--space-2) var(--space-3);
}

.sh__mint .label {
  color: var(--text-dim);
}

.sh__input {
  font: inherit;
  font-size: var(--fs-data);
  color: var(--text);
  background: var(--bg-0);
  border: 1px solid var(--hairline-lit);
  padding: var(--space-1) var(--space-2);
}

.sh__input:focus {
  outline: none;
  border-color: var(--teal-hot);
}

.sh__submit {
  grid-column: 2;
  justify-self: start;
  margin-top: var(--space-1);
  padding: var(--space-1) var(--space-3);
  border: 1px solid var(--teal);
  color: var(--teal-hot);
  font-size: var(--fs-micro);
  letter-spacing: 0.14em;
  text-transform: uppercase;
  transition: background 0.2s, color 0.2s;
}

.sh__submit:hover:not(:disabled) {
  background: var(--teal);
  color: var(--bg-0);
}

.sh__submit:disabled {
  opacity: 0.5;
  cursor: default;
}

.sh__minted,
.sh__head {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--space-2);
  margin-top: var(--space-3);
}

.sh__url {
  font-family: var(--font-mono);
  font-size: var(--fs-data);
  color: var(--teal-hot);
  word-break: break-all;
}

.sh__btn {
  color: var(--text-faint);
}

.sh__btn:hover {
  color: var(--teal-hot);
}

.sh__tok {
  font-family: var(--font-mono);
  font-size: var(--fs-data);
  color: var(--teal-hot);
  letter-spacing: 0.1em;
}

.sh__tok--on,
.sh__tok:hover {
  text-decoration: underline;
}

.sh__chips {
  display: inline-flex;
  flex-wrap: wrap;
  gap: var(--space-1);
}

.sh__chip {
  padding: 0 var(--space-1);
  border: 1px solid var(--hairline);
  color: var(--text-dim);
  line-height: 1.6;
  white-space: nowrap;
}

.sh__chip--on {
  border-color: var(--teal);
  color: var(--teal-hot);
}

.sh__fwd {
  color: var(--amber);
  white-space: nowrap;
}

.sh__quiet {
  color: var(--text-faint);
}

.sh__state {
  color: var(--green);
  margin-right: var(--space-2);
}

.sh__state--off {
  color: var(--text-faint);
}

.sh__kind {
  padding: 0 var(--space-1);
  border: 1px solid var(--hairline-lit);
  color: var(--text-dim);
  line-height: 1.6;
}

.sh__kind--view {
  border-color: var(--teal);
  color: var(--teal-hot);
}

.sh__kind--unfurl {
  border-color: var(--amber);
  color: var(--amber);
}

.sh__prose {
  margin-top: var(--space-2);
  font-size: var(--fs-data);
  color: var(--text);
}

.sh__verdict {
  margin-top: var(--space-2);
  color: var(--text-dim);
}
</style>
